title: RedCorr's Blog
description: >-
  记录一些文字。
baseurl: ""
url: "https://redcorr.github.io"
theme: null

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

exclude:
  - Gemfile
  - Gemfile.lock
